"""
Table generation for the paper.
Produces both CSV (for analysis) and LaTeX (for direct inclusion in the manuscript).
"""

from pathlib import Path

import numpy as np
import pandas as pd


def _fmt(value, decimals: int = 3) -> str:
    if isinstance(value, float) and np.isnan(value):
        return "—"
    if isinstance(value, float):
        return f"{value:.{decimals}f}"
    return str(value)


# ─────────────────────────────────────────────
# Table 1 — Main ablation results
# ─────────────────────────────────────────────
def build_main_results_table(summary_records: list[dict]) -> pd.DataFrame:
    """
    Build the main results DataFrame.

    Each record must contain:
      model, group, accuracy_mean, accuracy_std,
      f1_macro_mean, f1_macro_std, roc_auc_mean, roc_auc_std, mcc_mean, mcc_std,
      [optional: ci_lower, ci_upper for each metric]
    """
    df = pd.DataFrame(summary_records)

    # Sort: by group then by mcc_mean descending
    df = df.sort_values(["group", "mcc_mean"], ascending=[True, False])
    df = df.reset_index(drop=True)

    return df


def save_results_table(df: pd.DataFrame, output_dir: Path, name: str = "main_results") -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_dir / f"{name}.csv", index=False)
    _to_latex(df, output_dir / f"{name}.tex", name)


def _to_latex(df: pd.DataFrame, path: Path, caption: str) -> None:
    """Generate a publication-ready LaTeX table."""
    cols = ["model", "group", "accuracy_mean", "f1_macro_mean", "roc_auc_mean", "mcc_mean"]
    std_cols = {
        "accuracy_mean": "accuracy_std",
        "f1_macro_mean": "f1_macro_std",
        "roc_auc_mean":  "roc_auc_std",
        "mcc_mean":      "mcc_std",
    }
    display_cols = {
        "model": "Model",
        "group": "Group",
        "accuracy_mean": "Accuracy",
        "f1_macro_mean": "F1 Macro",
        "roc_auc_mean":  "AUC-ROC",
        "mcc_mean":      "MCC",
    }

    # Find best value per metric column (for bolding)
    metric_cols = ["accuracy_mean", "f1_macro_mean", "roc_auc_mean", "mcc_mean"]
    best = {col: df[col].max() for col in metric_cols if col in df.columns}

    lines = [
        "% Auto-generated by onchain_direction/src/visualization/tables.py",
        "\\begin{table}[htbp]",
        "\\centering",
        f"\\caption{{Ablation Study Results — Mean ± Std over Walk-Forward Folds}}",
        f"\\label{{tab:{caption}}}",
        "\\begin{tabular}{llcccc}",
        "\\toprule",
        " & ".join(display_cols[c] for c in cols if c in display_cols) + " \\\\",
        "\\midrule",
    ]

    prev_group = None
    for _, row in df.iterrows():
        if row.get("group") != prev_group and prev_group is not None:
            lines.append("\\midrule")
        prev_group = row.get("group")

        cells = []
        for col in cols:
            if col in ("model", "group"):
                cells.append(str(row.get(col, "")))
            elif col in metric_cols:
                mean_val = row.get(col, float("nan"))
                std_val = row.get(std_cols.get(col, ""), float("nan"))
                ci_low = row.get(col.replace("_mean", "_ci_lower"), None)
                ci_high = row.get(col.replace("_mean", "_ci_upper"), None)

                mean_str = _fmt(mean_val)
                if ci_low is not None and ci_high is not None:
                    cell = f"{mean_str} [{_fmt(ci_low)}, {_fmt(ci_high)}]"
                else:
                    std_str = _fmt(std_val)
                    cell = f"{mean_str} ± {std_str}"

                # Bold best value
                if not np.isnan(mean_val) and abs(mean_val - best.get(col, float("inf"))) < 1e-6:
                    cell = f"\\textbf{{{cell}}}"
                cells.append(cell)

        lines.append(" & ".join(cells) + " \\\\")

    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


# ─────────────────────────────────────────────
# Table 2 — Statistical significance matrix
# ─────────────────────────────────────────────
def build_significance_table(pairwise_results: dict, output_dir: Path) -> None:
    """
    Build and save a p-value matrix as CSV and LaTeX.
    pairwise_results from statistical_tests.run_pairwise_comparisons().
    """
    matrix = pairwise_results["matrix"]
    ids = sorted(matrix.keys())
    alpha = pairwise_results.get("alpha", 0.05)

    rows = []
    for id_a in ids:
        row = {"experiment": id_a}
        for id_b in ids:
            pval = matrix[id_a].get(id_b, float("nan"))
            row[id_b] = pval
        rows.append(row)

    df = pd.DataFrame(rows).set_index("experiment")
    output_dir.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_dir / "significance_pvalue_matrix.csv")

    # LaTeX with significance highlighting
    lines = [
        "% P-value matrix (Wilcoxon + Bonferroni correction)",
        "\\begin{table}[htbp]",
        "\\centering",
        f"\\caption{{Pairwise Statistical Significance (Wilcoxon, Bonferroni-corrected, $\\alpha={alpha}$)}}",
        "\\label{tab:significance}",
        "\\resizebox{\\textwidth}{!}{",
        "\\begin{tabular}{l" + "c" * len(ids) + "}",
        "\\toprule",
        " & " + " & ".join(ids) + " \\\\",
        "\\midrule",
    ]
    for id_a in ids:
        cells = [id_a]
        for id_b in ids:
            pval = matrix[id_a].get(id_b, float("nan"))
            if id_a == id_b:
                cells.append("—")
            elif np.isnan(pval):
                cells.append("—")
            elif pval < alpha:
                cells.append(f"\\textbf{{{pval:.3f}}}*")
            else:
                cells.append(f"{pval:.3f}")
        lines.append(" & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "}", "\\end{table}"]

    with open(output_dir / "significance_pvalue_matrix.tex", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


# ─────────────────────────────────────────────
# Table 3 — Feature importance ranking
# ─────────────────────────────────────────────
def build_feature_importance_table(
    feature_importance: list[tuple[str, float]],
    model_name: str,
    group_name: str,
    output_dir: Path,
    top_n: int = 20,
) -> None:
    fi = feature_importance[:top_n]
    df = pd.DataFrame(fi, columns=["Feature", "Mean |SHAP|"])
    df.index = range(1, len(df) + 1)
    df.index.name = "Rank"

    output_dir.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_dir / f"feature_importance_{model_name}_{group_name}.csv")

    lines = [
        f"% Feature importance — {model_name} on {group_name}",
        "\\begin{table}[htbp]",
        "\\centering",
        f"\\caption{{Top-{top_n} Features by Mean |SHAP| — {model_name} ({group_name})}}",
        f"\\label{{tab:fi_{model_name}_{group_name}}}",
        "\\begin{tabular}{clr}",
        "\\toprule",
        "Rank & Feature & Mean |SHAP| \\\\",
        "\\midrule",
    ]
    for rank, (name, val) in enumerate(fi, 1):
        lines.append(f"{rank} & {name.replace('_', '\\_')} & {val:.4f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]

    with open(output_dir / f"feature_importance_{model_name}_{group_name}.tex", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
